language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
  - COMPOSER_FLAGS=''

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - bin/phpspec run -fpretty --verbose
